import { environment } from "../../../Core/Environments/Environment";

/*********************/
/*  DEV ENVIRONMENT  */
/*********************/

const DEV = {
  REQUEST_URL: "http://127.0.0.1:3000",
  EPS: [
    "Famisanar",
    "E.P.S. Sanitas",
    "Cafesalud",
    "Salud Total",
    "Salud Colmena",
  ],
  EstadoCivil: ["Soltero", "Casado", "Divorciado", "Union libre", "Viudo"],
  TipoSangre: ["A+", "A-", "B+", "B-", "O-", "O+"],
  Sexo: ["Hombre", "Mujer"],
  TipoDocumento: [
    "Tarjeta de identidad",
    "Cedula de Ciudadania",
    "Registro Civil",
    "Pasaporte",
  ],
  Rol: ["Administrador", "Doctor", "Laboratorista", "Paciente"],
  Departamento: [
    "Leticia",
    "Medelllin",
    "Arauca",
    "Barranquilla",
    "Bogota",
    "Cartagena",
    "Tunja",
    "Manizales",
    "Florencia",
    "Yopal",
    "Popayan",
    "Valledupar",
    "Quibdó",
    "Monteria",
    "Inirida",
    "San José del Guaviare",
    "Neiva",
    "Rioacha",
    "Santa Marta",
    "Villavicencio",
    "Pasto",
    "Cucuta",
    "Mocoa",
    "Armenia",
    "Pereira",
    "San andres",
    "Bucaramanga",
    "Sincelejo",
    "Ibague",
    "Cali",
    "Mitu",
    "Puerto carreño",
  ],
  TipoExamen: ["Tipo A", "Tipo B", "Tipo C"],
  EstadoExamen: [
    "Sin realizar",
    "Espera de resultados",
    "Por revisar",
    "Revisado",
  ],
};

/*********************/
/*  PROD ENVIRONMENT  */
/*********************/

const PROD = {
  REQUEST_URL: "https://127.0.0.1:3000",
  EPS: [
    "Famisanar",
    "E.P.S. Sanitas",
    "Cafesalud",
    "Salud Total",
    "Salud Colmena",
  ],
  EstadoCivil: ["Soltero", "Casado", "Divorciado", "Union libre", "Viudo"],
  TipoSangre: ["A+", "A-", "B+", "B-", "O-", "O+"],
  Sexo: ["Hombre", "Mujer"],
  TipoDocumento: [
    "Tarjeta de identidad",
    "Cedula de Ciudadania",
    "Registro Civil",
    "Pasaporte",
  ],
  Rol: ["Administrador", "Doctor", "Laboratorista", "Paciente"],
  Departamento: [
    "Leticia",
    "Medelllin",
    "Arauca",
    "Barranquilla",
    "Bogota",
    "Cartagena",
    "Tunja",
    "Manizales",
    "Florencia",
    "Yopal",
    "Popayan",
    "Valledupar",
    "Quibdó",
    "Monteria",
    "Inirida",
    "San José del Guaviare",
    "Neiva",
    "Rioacha",
    "Santa Marta",
    "Villavicencio",
    "Pasto",
    "Cucuta",
    "Mocoa",
    "Armenia",
    "Pereira",
    "San andres",
    "Bucaramanga",
    "Sincelejo",
    "Ibague",
    "Cali",
    "Mitu",
    "Puerto carreño",
  ],
  TipoExamen: ["Tipo A", "Tipo B", "Tipo C"],
  EstadoExamen: [
    "Sin realizar",
    "Espera de resultados",
    "Por revisar",
    "Revisado",
  ],
};

export const CONSTANTS = environment.production === true ? PROD : DEV;
