export const Pacients = [
  {
    Nombres: "Josh",
    Apellidos: "Ryan",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 14856073,
    FechaNacimiento: "03/12/1976",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "soltero",
    EPS: "famisanar",
    NombresContactoEmergencia: "Natalia",
    ApellidosContactoEmergencia: "Ryan",
    Parentesco: "Hermana",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Theresa",
    Apellidos: "Weep",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 143567855,
    FechaNacimiento: "03/07/1986",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Jhon",
    ApellidosContactoEmergencia: "Weep",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
  },

  {
    Nombres: "Darrell",
    Apellidos: "Steward",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 35358976,
    FechaNacimiento: "03/12/2006",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    NombresContactoEmergencia: "Carolione",
    ApellidosContactoEmergencia: "Steward",
    Parentesco: "Abuela",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Dianne",
    Apellidos: "Russell",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 101034957,
    FechaNacimiento: "03/12/1966",
    Sexo: "Femenino",
    TipoSangre: "B+",
    EstadoCivil: "Union libre",
    EPS: "E.P.S Sanitas",
    NombresContactoEmergencia: "Jane",
    ApellidosContactoEmergencia: "Russell",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Savannah",
    Apellidos: "Nguyen",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1990",
    Sexo: "Femenino",
    TipoSangre: "A+",
    EstadoCivil: "Union libre",
    EPS: "Famisanar",
    NombresContactoEmergencia: "Carl",
    ApellidosContactoEmergencia: "Nguyen",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Jane",
    Apellidos: "Cooper",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 131048675,
    FechaNacimiento: "03/12/1976",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Vincent",
    ApellidosContactoEmergencia: "Cooper",
    Parentesco: "Primo",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Darlene",
    Apellidos: "Robertson",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 18492384,
    FechaNacimiento: "03/12/1979",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Bart",
    ApellidosContactoEmergencia: "Robertson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Courtney",
    Apellidos: "Henry",
    TipoDocumento: "Registro Civil",
    NumeroDocumento: 34562323,
    FechaNacimiento: "03/12/1996",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Criss",
    ApellidosContactoEmergencia: "Henry",
    Parentesco: "Abuelo",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Devon",
    Apellidos: "Lane",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 47564789,
    FechaNacimiento: "03/12/1956",
    Sexo: "Masculino",
    TipoSangre: "B+",
    EstadoCivil: "Casado",
    EPS: "Compensar",
    NombresContactoEmergencia: "Tonny",
    ApellidosContactoEmergencia: "Lane",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Jerome",
    Apellidos: "Bell",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 10492837,
    FechaNacimiento: "03/12/2000",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Arnold",
    ApellidosContactoEmergencia: "Bell",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Cameron",
    Apellidos: "Williamson",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 20103456,
    FechaNacimiento: "03/12/2002",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    NombresContactoEmergencia: "Hendry",
    ApellidosContactoEmergencia: "Williamson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
  },
  {
    Nombres: "Katrhyn",
    Apellidos: "Murphy",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 1011097651,
    FechaNacimiento: "03/12/2002",
    Sexo: "Femenino",
    TipoSangre: "B+",
    EstadoCivil: "Viudo",
    EPS: "Famisanar",
    NombresContactoEmergencia: "Devis",
    ApellidosContactoEmergencia: "Murphy",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
  },
];
