import { PacientInfo } from "../../../Core/Models/exams-modals";

export const Pacients: PacientInfo[] = [
  {
    Nombres: "Josh",
    Apellidos: "Ryan",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 14856073,
    FechaNacimiento: "03/12/1976",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "soltero",
    EPS: "famisanar",
    NombresContactoEmergencia: "Natalia",
    ApellidosContactoEmergencia: "Ryan",
    Parentesco: "Hermana",
    TelefonoContacto: 45678965,
    exams: [],
  },
  {
    Nombres: "Theresa",
    Apellidos: "Weep",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 143567855,
    FechaNacimiento: "03/07/1986",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Jhon",
    ApellidosContactoEmergencia: "Weep",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Theresa Weep ",
        NumeroDocumento: "143567855",
        TipoExamen: "Tipo A",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Theresa Weep",
        NumeroDocumento: "45678965",
        TipoExamen: "Tipo B",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: " Esperando resultados",
        NombrePaciente: "Theresa Weep",
        NumeroDocumento: "45678965",
        TipoExamen: "Tipo A",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Theresa Weep",
        NumeroDocumento: "45678965",
        TipoExamen: "Tipo A",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Theresa Weep",
        NumeroDocumento: "45678965",
        TipoExamen: "Tipo C",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Theresa Weep",
        NumeroDocumento: "45678965",
        TipoExamen: "Tipo A",
        Resultados: "Theresa_Weep.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },

  {
    Nombres: "Darrell",
    Apellidos: "Steward",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 35358976,
    FechaNacimiento: "03/12/2006",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    NombresContactoEmergencia: "Carolione",
    ApellidosContactoEmergencia: "Steward",
    Parentesco: "Abuela",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo A",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo B",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo A",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo B",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo A",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Darrell Steward",
        NumeroDocumento: "35358976",
        TipoExamen: "Tipo C",
        Resultados: "Darrell_Steward.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
  {
    Nombres: "Dianne",
    Apellidos: "Russell",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 101034957,
    FechaNacimiento: "03/12/1966",
    Sexo: "Femenino",
    TipoSangre: "B+",
    EstadoCivil: "Union libre",
    EPS: "E.P.S Sanitas",
    NombresContactoEmergencia: "Jane",
    ApellidosContactoEmergencia: "Russell",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo A",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo B",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo C",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo A",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo B",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Dianne Russell",
        NumeroDocumento: "101034957",
        TipoExamen: "Tipo A",
        Resultados: "Dianne_Russell.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
  {
    Nombres: "Savannah",
    Apellidos: "Nguyen",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1990",
    Sexo: "Femenino",
    TipoSangre: "A+",
    EstadoCivil: "Union libre",
    EPS: "Famisanar",
    NombresContactoEmergencia: "Carl",
    ApellidosContactoEmergencia: "Nguyen",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    exams: [],
  },
  {
    Nombres: "Jane",
    Apellidos: "Cooper",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 131048675,
    FechaNacimiento: "03/12/1976",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Vincent",
    ApellidosContactoEmergencia: "Cooper",
    Parentesco: "Primo",
    TelefonoContacto: 45678965,
    exams: [],
  },
  {
    Nombres: "Darlene",
    Apellidos: "Robertson",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 18492384,
    FechaNacimiento: "03/12/1979",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Bart",
    ApellidosContactoEmergencia: "Robertson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    exams: [],
  },
  {
    Nombres: "Courtney",
    Apellidos: "Henry",
    TipoDocumento: "Registro Civil",
    NumeroDocumento: 34562323,
    FechaNacimiento: "03/12/1996",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Criss",
    ApellidosContactoEmergencia: "Henry",
    Parentesco: "Abuelo",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo A",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo A",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo B",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo C",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo C",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Courtney Henry",
        NumeroDocumento: "34562323",
        TipoExamen: "Tipo A",
        Resultados: "Courtney_Henry.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
  {
    Nombres: "Devon",
    Apellidos: "Lane",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 47564789,
    FechaNacimiento: "03/12/1956",
    Sexo: "Masculino",
    TipoSangre: "B+",
    EstadoCivil: "Casado",
    EPS: "Compensar",
    NombresContactoEmergencia: "Tonny",
    ApellidosContactoEmergencia: "Lane",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo A",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo B",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo B",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo A",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo C",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Devon Lane",
        NumeroDocumento: "47564789",
        TipoExamen: "Tipo A",
        Resultados: "Devon_Lane.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
  {
    Nombres: "Jerome",
    Apellidos: "Bell",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 10492837,
    FechaNacimiento: "03/12/2000",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    NombresContactoEmergencia: "Arnold",
    ApellidosContactoEmergencia: "Bell",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    exams: [],
  },
  {
    Nombres: "Cameron",
    Apellidos: "Williamson",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 20103456,
    FechaNacimiento: "03/12/2002",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    NombresContactoEmergencia: "Hendry",
    ApellidosContactoEmergencia: "Williamson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo A",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo A",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo B",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo B",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo A",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Revisado",
        NombrePaciente: "Cameron Williamson",
        NumeroDocumento: "20103456",
        TipoExamen: "Tipo C",
        Resultados: "Cameron_Williamson.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
  {
    Nombres: "Katrhyn",
    Apellidos: "Murphy",
    TipoDocumento: "Tarjeta de identidad",
    NumeroDocumento: 1011097651,
    FechaNacimiento: "03/12/2002",
    Sexo: "Femenino",
    TipoSangre: "B+",
    EstadoCivil: "Viudo",
    EPS: "Famisanar",
    NombresContactoEmergencia: "Devis",
    ApellidosContactoEmergencia: "Murphy",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    exams: [
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo B",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Esperando resultados",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo A",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo B",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Sin realizar",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo A",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Por revisar",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo C",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
      {
        nombre: "Nombre de examen",
        estado: "Revisado",
        NombrePaciente: "Katrhyn Murphy",
        NumeroDocumento: "1011097651",
        TipoExamen: "Tipo A",
        Resultados: "Katrhyn_Murphy.pdf",
        Observaciones:
          "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
      },
    ],
  },
];
