import { infoUsers } from "../../../Core/Models/info-users-modals";

export const InfoUsers: infoUsers[] = [
  {
    Nombres: "Josh",
    Apellidos: "Ryan",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1976",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "soltero",
    EPS: "famisanar",
    Ciudad: "medellin",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Josh.ryan@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Natalia",
    ApellidosContactoEmergencia: "Ryan",
    Parentesco: "Hermana",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
  {
    Nombres: "Theresa",
    Apellidos: "Weep",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/07/1986",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Theresa.Weep@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Jhon",
    ApellidosContactoEmergencia: "Weep",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Laboratorista",
    Contraseña: "*********",
  },
  {
    Nombres: "Kathryn ",
    Apellidos: "Murphy",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/02/1996",
    Sexo: "Femenino",
    TipoSangre: "A+",
    EstadoCivil: "Viudo",
    EPS: "Compensar",
    Ciudad: "Cali",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Kathryn.Murphy@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Karen",
    ApellidosContactoEmergencia: "Murphy",
    Parentesco: "Tia",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Doctor",
    Contraseña: "*********",
  },
  {
    Nombres: "Darrell",
    Apellidos: "Steward",
    TipoDocumento: "Tarjeta de Identidad",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/2006",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Darrell.Steward@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Carolione",
    ApellidosContactoEmergencia: "Steward",
    Parentesco: "Abuela",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Paciente",
    Contraseña: "*********",
  },
  {
    Nombres: "Dianne",
    Apellidos: "Russell",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1966",
    Sexo: "Femenino",
    TipoSangre: "B+",
    EstadoCivil: "Union libre",
    EPS: "E.P.S Sanitas",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Dianne.Russell@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Jane",
    ApellidosContactoEmergencia: "Russell",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
  {
    Nombres: "Savannah",
    Apellidos: "Nguyen",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1990",
    Sexo: "Femenino",
    TipoSangre: "A+",
    EstadoCivil: "Union libre",
    EPS: "Famisanar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Savannah.Nguyen@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Carl",
    ApellidosContactoEmergencia: "Nguyen",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Laboratorista",
    Contraseña: "*********",
  },
  {
    Nombres: "Jane",
    Apellidos: "Cooper",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1976",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Jane.Cooper@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Vincent",
    ApellidosContactoEmergencia: "Cooper",
    Parentesco: "Primo",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
  {
    Nombres: "Darlene",
    Apellidos: "Robertson",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1979",
    Sexo: "Masculino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Darlene.Robertson@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Bart",
    ApellidosContactoEmergencia: "Robertson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Laboratorista",
    Contraseña: "*********",
  },
  {
    Nombres: "Courtney",
    Apellidos: "Henry",
    TipoDocumento: "Pasaporte",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1996",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Courtney.Henry@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Criss",
    ApellidosContactoEmergencia: "Henry",
    Parentesco: "Abuelo",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Doctor",
    Contraseña: "*********",
  },
  {
    Nombres: "Devon",
    Apellidos: "Lane",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/1956",
    Sexo: "Masculino",
    TipoSangre: "B+",
    EstadoCivil: "Casado",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Devon.Lane@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Tonny",
    ApellidosContactoEmergencia: "Lane",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
  {
    Nombres: "Jerome",
    Apellidos: "Bell",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/2000",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Union libre",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Jerome.Bell@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Arnold",
    ApellidosContactoEmergencia: "Bell",
    Parentesco: "Hermano",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
  {
    Nombres: "Cameron",
    Apellidos: "Williamson",
    TipoDocumento: "Cedula de Ciudadania",
    NumeroDocumento: 43567897,
    FechaNacimiento: "03/12/2002",
    Sexo: "Femenino",
    TipoSangre: "O+",
    EstadoCivil: "Soltero",
    EPS: "Compensar",
    Ciudad: "Bogota",
    DireccionResidencia: "Cll 152 A # 7- 49",
    CorreoElectronico: "Cameron.Williamson@ejemeplo.com",
    Celular: 43256734,
    TelefonoFijo: 3456789,
    TelefonoOficina: 3546758,
    NombresContactoEmergencia: "Hendry",
    ApellidosContactoEmergencia: "Williamson",
    Parentesco: "Tio",
    TelefonoContacto: 45678965,
    Profesion: "Medico",
    Rol: "Administrador",
    Contraseña: "*********",
  },
];
